services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres.onxdgcvmsygkxnwpdryn:fygbis-womce0-jectuR@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
    restart: always